---
# Deploy on local
- name: Pull code tags
  shell: cd {{path_project}} && git clone -b {{tag_name}} {{repository}}
  sudo: no
  
- name: Rename folder project
  shell: mv {{path_project}}/bachviet {{path_project}}/{{tag_name}}
  
- name: Remove old htdocs
  shell: rm -rf {{path_project}}/htdocs
  
- name: Create symbolic link htdocs
  shell: cd {{path_project}} && ln -sf {{tag_name}}/htdocs .
  
  notify:
    - Restart Apache
    
- name: Migrate App
  django_manage: >
      command=migrate
      app_path={{app_path}}
      pythonpath={{python_path}}
      virtualenv={{venv}}

- name: Syncdb App
  django_manage: >
      command=syncdb
      app_path={{app_path}}
      pythonpath={{python_path}}
      virtualenv={{venv}}